CREATE DATABASE IF NOT EXISTS sisai
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE sisai;

CREATE TABLE clientes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);

CREATE TABLE usuarios (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(254) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    nome VARCHAR(150) NOT NULL,

    PRIMARY KEY (id),
    UNIQUE KEY uk_usuarios_email (email)
);
